bot-account: 123  # QQ bot account
bot-password: 'No_BUG_Report'  # QQ bot password

player-group: 10000  # the number of QQ group where players are in
inner-player-group: 10010  # not very useful, just ignore it
op-group: 10086  # the group where managers and operators in

QWeather-APIKey: 'qwq'  # 和风天气API密钥

message-length-limit: 60  # chars  # the maximum of a group message to be transferred to the MC server
bot-speak-possibility: 5  # percent  # bot may seldom speak something written at "messages.yml" - "bot-greetings", set this number to decide the possibility
keep-inv-cost: 40  #pts  # (ONLY for CatLand, EconomyX is needed)
haste-per-minute-cost: 3.0  #pts  # (ONLY for CatLand, EconomyX is needed)

tps-check:
  enabled: true
  cron: '0 0/1 * * * ?'  # to decide the frequency of TPS-Check
  threshold: 17.0  # ticks  # when server TPS is lower than this number, send a warning message to the op-group above

daily-greetings:
  morning:
    enabled: true
    cron: '0 0 7 * * ?'
  night:
    enabled: true
    cron: '0 0 23 * * ?'

inner-player-group-auto-manage:
  invite:
    enabled: true
    cron: '0 0 0/1 * * ?'
    requirement: 1000  # minutes per week
    blacklist:
      - 'qwq'
      - 'qaq'
  kick:
    enabled: true
    cron: '0 0 18 ? * 7'
    requirement: 1000
    whitelist:
      - 'Maplef_snow'
      - 'xinQi5'